#!/bin/bash
username=$USER
date=$(date +%c)
hostname=$(hostname -s)
source /etc/os-release
osname=$PRETTY_NAME
timeup=$(uptime -p)
cpu=$(lscpu | grep 'Model name: '| awk -F ': ' ' {print $2} ')
cpuspeed=$(sudo dmidecode -t processor | grep -m 1 "Max Speed")
ramsize=$(free -m | grep Mem: | awk '{print $2}')
installeddisks=$(lsblk -dno KNAME,TYPE,SIZE,MODEL)
installedvideocard=$(lspci -v | grep VGA -A 3)
domainname=$(dnsdomainname)
FQDN=$hostname.$domainname
hostaddress=$(getent ahosts "$HOSTNAME" | grep STREAM | head -n 1 | cut -d ' ' -f1)
gateway=$(ip route show default | grep default | awk '{print $3}')
dns=$(grep nameserver /etc/resolv.conf | awk '{print $2}')
loggedinusers=$(who | awk '{print $1}')
diskspace=$(df -hP | grep -v "^Filesystem" | awk '{print $1, $5}')
processCount=$(ps aux | wc -l)
loadAverages=$(uptime | awk '{print $NF-2, $NF-1, $NF}')
memoryAllocation=$(free -m | grep Mem: | awk '{print $2, $3, $4}')
listeningNetworkPorts=$(ss -ltn | grep LISTEN)
ufwRules=$(ufw status verbose)


cat <<EOF

System Report generated by $username, $date
 
System Information
------------------
Hostname: $hostname
OS: $osname
Uptime: $timeup
 
Hardware Information
--------------------
cpu:  $cpu
Speed:$cpuspeed
Ram: $ramsize     
Disk(s): $installeddisks
Video: $installedvideocard
 
Network Information
-------------------
FQDN: $FQDN
Host Address:  $hostaddress
Gateway IP:  $gateway
DNS Server:   $dns
 
InterfaceName: MAKE AND MODEL OF NETWORK CARD
IP Address: IP Address in CIDR format
 
System Status
-------------
Users Logged In: $loggedinusers
Disk Space: $diskspace
Process Count: $processCount
Load Averages: $loadAverages
Memory Allocation:  $memoryAllocation
Listening Network Ports:  $listeningNetworkPorts
UFW Rules:$ufwRules

EOF
